rgou_bootstrap:
    pattern:  /
    defaults: { _controller: RgouBootstrapBundle:Default:index }

rgou_bootstrap_base:
    pattern:  /base
    defaults: { _controller: RgouBootstrapBundle:Default:base }

rgou_bootstrap_components:
    pattern:  /components
    defaults: { _controller: RgouBootstrapBundle:Default:components }

rgou_bootstrap_extend:
    pattern:  /extend
    defaults: { _controller: RgouBootstrapBundle:Default:extend }

rgou_bootstrap_getting_started:
    pattern:  /getting-started
    defaults: { _controller: RgouBootstrapBundle:Default:gettingStarted }

rgou_bootstrap_javascript:
    pattern:  /javascript
    defaults: { _controller: RgouBootstrapBundle:Default:javascript }

rgou_bootstrap_customize:
    pattern:  /customize
    defaults: { _controller: RgouBootstrapBundle:Default:customize }

rgou_bootstrap_scaffolding:
    pattern:  /scaffolding
    defaults: { _controller: RgouBootstrapBundle:Default:scaffolding }

rgou_bootstrap_font_awesome:
    pattern:  /font-awesome
    defaults: { _controller: RgouBootstrapBundle:Default:fontAwesome }

rgou_bootstrap_example_starter:
    pattern:  /example/starter-template
    defaults: { _controller: RgouBootstrapBundle:Default:exampleStarter }

rgou_bootstrap_example_hero:
    pattern:  /example/hero
    defaults: { _controller: RgouBootstrapBundle:Default:exampleHero }

rgou_bootstrap_example_fluid:
    pattern:  /example/fluid
    defaults: { _controller: RgouBootstrapBundle:Default:exampleFluid }

rgou_bootstrap_example_marketing_narrow:
    pattern:  /example/marketing-narrow
    defaults: { _controller: RgouBootstrapBundle:Default:exampleMarketingNarrow }

rgou_bootstrap_example_signin:
    pattern:  /example/signin
    defaults: { _controller: RgouBootstrapBundle:Default:exampleSignin }

rgou_bootstrap_example_sticky_footer_navbar:
    pattern:  /example/sticky-footer-navbar
    defaults: { _controller: RgouBootstrapBundle:Default:exampleStickyFooterNavbar }

rgou_bootstrap_example_sticky_footer:
    pattern:  /example/sticky-footer
    defaults: { _controller: RgouBootstrapBundle:Default:exampleStickyFooter }

rgou_bootstrap_example_carousel:
    pattern:  /example/carousel
    defaults: { _controller: RgouBootstrapBundle:Default:exampleCarousel }

rgou_bootstrap_example_justified_nav:
    pattern:  /example/justified-nav
    defaults: { _controller: RgouBootstrapBundle:Default:exampleJustifiedNav }



