parameters:
#    rgou_bootstrap.example.class: Rgou\BootstrapBundle\Example

services:

    rgou_bootstrap.util.inflector:
        class: Rgou\BootstrapBundle\Util\Inflector
  
    rgou_bootstrap.util.mongodb:
        class: Rgou\BootstrapBundle\Util\MongoDB
  
    rgou_bootstrap.twig.globals:
        class: Rgou\BootstrapBundle\Twig\Extension\GlobalsExtension
        arguments: ["@service_container"]        
        tags:
            - { name: twig.extension }  
  
    rgou_bootstrap.menu_builder:
        class: Rgou\BootstrapBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    rgou_bootstrap.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: rgou_bootstrap.menu_builder
        factory_method: mainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main }

    rgou_bootstrap.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: rgou_bootstrap.menu_builder
        factory_method: mainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: samplemain }

    rgou_bootstrap.menu.user:
        class: Knp\Menu\MenuItem
        factory_service: rgou_bootstrap.menu_builder
        factory_method: userMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: sampleuser }